# Generated by Django 6.0.7 on 2026-07-13 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0002_valoracion_primera_optativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
